# Site settings
title: tomhoover [dot] net
author: Tom Hoover
email: tom@tomhoover.net
description: > # this means to ignore newlines until "baseurl:"
 tomhoover.net...my own little speedbump on the information superhighway.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tomhoover.net" # the base hostname & protocol for your site
twitter_username: tom_hoover
github_username:  tomhoover

# Build settings
markdown: kramdown
permalink: /:title/
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
